### ISSUE TITLE
When adding a new line to an existing document, why does the screen scroll down one or two lengths?

### ISSUE THREAD

**Issue by virtadpt** [alextselegidis/plainpad#10]
Hi.  I've noticed this particular quirk on both Chrome for OSX and Firefox for 64-bit Linux: Every two or three times I click into a pre-existing note in a self-hosted Plainpad install, for some reason the displayed text of the note scrolls down one or two screen lengths, and I find myself typing blind until I scroll the browser back up.  Is this a known quirk in the text editor .js library used, or is it something else at work?

**Comment by alextselegidis** [comment]
Hello @virtadpt 

This is indeed an issue I also saw myself. 

I suspect that it has to do with the content being updated while the editor scroll height gets adjusted, meaning that this is a timing issue and thus only happens randomly. 

I will do some further testing and remove this issue so that the editor scroll position stays the same no matter the change. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello @virtadpt 

There's a new Plainpad version that also addresses this problem. 

This is the final pre-release before the final v1.0.0 release. 

Hello Clemens,

I hope this finds you well. 

It's been a while since we last talked, there was some vacation time in between and concentration on other projects, but there is a new Plainpad version. 

This will be the last pre-release before the final v1.0.0 and features an important offline PWA fix (when you start the app in offline mode it used to not display notes on the list until you search).

I also upgrade the framework behind the API which now uses Laravel 8. For this update you will need to make sure your server is running PHP 7.3+ 

Here's how to update:

* Ensure you are running PHP 7.3+ 
* Ensure the entire Plainpad directory is writable 777
* Go to the settings page and click the update button 
* An error will be displayed due to the laravel upgrade, that's ok
* Finalize the upgrade by running "php artisan refresh" on your console. 

If you have errors check the following places for information: 

* storage/logs/update-***.log for updater logs
* storage/logs/laravel-***.log for framework logs
* /var/log/apache2|nginx/error.log for server logs

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
