### ISSUE TITLE
Cannot login after a fresh self-hosting install

### ISSUE THREAD

**Issue by LukePolque** [alextselegidis/plainpad#11]
Hi,

I created a new virtual server, securing it with LetsEncrypt, using PostgreSQL and everything worked fine. Also, I run an artisan to install everything.

However, trying to login as admin@example.org with password 12345 always returns me to a login page. I tried to change email address manually in the database, but I end up with the issue - not able to change password.

Any help?

Thanks,

Lukas

**Comment by alextselegidis** [comment]
Hello @LukePolque 

It seems that the server cannot authorize your request. 

If you are using Apache, make sure that you use the `AllowOverride All` directive for your installation, so that the `.htaccess` file located in the public directly takes effect. 

If you are using NGINX you will need to make sure that the `Authorization` header does not get removed before the PHP processing starts. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ghost** [comment]
In case anyone has this same issue with signing in and has already followed the steps above and is also using Apache, make sure that the owner of your root html directory and all subfolders are owned by Apache.

In my case, running on Ubuntu, I ran the following command:

```chown -R www-data:www-data /var/www/html```

I was then able to log in successfully.

On a Red Hat based system, I would run:

```chown -R apache:apache /var/www/html```
