### ISSUE TITLE
multi os client 

### ISSUE THREAD

**Issue by gwlegion** [alextselegidis/plainpad#36]
is there a plan to make the server compatible with some client ... not really usefull for computers, but for smartphone this could be great !

**Comment by alextselegidis** [comment]
Hello! 

That might come in the future but since the frontend is a full featured PWA with offline capabilities there is no urgency to proceed with the implementation of desktop or mobile clients. 

Instead I'm going to focus more on the development of new features. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
